# Generated by Django 5.1.4 on 2025-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_photographs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
