# Generated by Django 5.1.4 on 2025-01-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_photographs_photo_alter_photographs_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographs',
            old_name='description',
            new_name='credit',
        ),
    ]
