# Generated by Django 5.1.4 on 2025-01-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_photographs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='publication',
            field=models.BooleanField(default=True),
        ),
    ]
