# Generated by Django 5.1.4 on 2025-01-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='category',
            field=models.CharField(choices=[('Nebulosa', 'Nebulosa'), ('Estrela', 'Estrela'), ('Galáxia', 'Galáxia'), ('Planeta', 'Planeta')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photographs',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
