# Generated by Django 5.1.4 on 2025-01-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_photographs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
