# Generated by Django 5.1.4 on 2025-01-09 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_photographs_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='date_publication',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
